[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/login/system/"
  to = "/.netlify/functions/login-system"
  status = 200

[[redirects]]
  from = "/api/login/admin/"
  to = "/.netlify/functions/login-admin"
  status = 200

[[redirects]]
  from = "/api/config/cloudinary/"
  to = "/.netlify/functions/cloudinary-config"
  status = 200
